#!/bin/bash

# Prints out the bluetooth status

BLUETOOTH_ON_ICON=''
BLUETOOTH_OFF_ICON=''

get_bluetooth()
{
    status=$(systemctl is-active bluetooth.service)
    perc=$(bluetoothctl info | grep "Battery Percentage" | awk -F '(' '{print $2}' | awk -F ')' '{print $1}')
    name=$(bluetoothctl info | grep "Name" | awk -F ':' '{print $2}')

    if [ "$status" == "active" ]
    then
        echo "$BLUETOOTH_ON_ICON $name 󰂂 $perc %"
    else
        echo ""
    fi
}

get_bluetooth
