#!/bin/bash

# Prints out the total disk memory and the available memory

PREFIX=' '

get_disk()
{
    echo $PREFIX $(df -h --total | head -5 | tail -1 | awk 'BEGIN { FS = " " } { print $3 "/" $2 " " $5 }')
}

get_disk
