#!/bin/bash

# Prints out if there is an ethernet cable connected

ETHERNET_ICON=''

get_ethernet()
{
    if [ -d /sys/class/net/enp0s31f6 ]; then
        if [ "$(cat /sys/class/net/enp0s31f6/carrier)" == "1" ]; then
          ip=$(curl -s ifconfig.co)
            echo "$ETHERNET_ICON $ip"
        fi
    fi
}

get_ethernet
